Add Romanian translation
bitcoinz-sites/btcz.rocks pull request #48
Opened 2018-03-16 15:53 UTC by egyptianbman

@awreeoh on Discord was kind enough to provide us with Romanian
translations!

2018-03-16 16:02 UTC, cryptorex approved these changes
that romanian is very accurate

2018-03-16 16:18 UTC, faneaatiku requested changes

2018-03-16 16:18 UTC, faneaatiku commented on translation/languages/ro.csv
> +- Niciodată nu primi / trimite nimănui cheile tale private. Cheile private trebuiesc ţinute în siguranţă. Îşi poţi recupera portofelele cu ajutorul lor. Dacă ii dai sau ii trimiâi cuiva cheia ta priv
"trimiâi" should be "trimiți"

2018-03-16 16:18 UTC, faneaatiku commented on translation/languages/ro.csv
> +"Our community is active and we are always developing. <br>You can follow us in social networks, on the forum, as well as Slack","Avem o comunitate activă care dezvolta continuu. <br>
"dezvolta" to "dezvoltă"

2018-03-16 16:18 UTC, faneaatiku commented on translation/languages/ro.csv
> +Ne poţi urmări in reţelele sociale, pe forum sau pe Slack. "
"in" to "în"

2018-03-16 16:18 UTC, faneaatiku commented on translation/languages/ro.csv
> +Our community is actively developing and growing every day.,Comunitatea noastră dezvoltă şi creşte în fiecare zi.
there should be a "se" between "noastră" and "dezvoltă" and become "noastră se dezvoltă"

2018-03-16 16:20 UTC, faneaatiku commented
It looks good leaving aside what i suggested.

2018-03-16 16:21 UTC, awreeoh commented
sorry about those mistakes guys... it was also a hard day at work :")

2018-03-16 23:53 UTC, egyptianbman commented
@faneaatiku let me know if this looks good now; thanks!

2018-03-17 00:48 UTC, faneaatiku commented
Everything fine! Thanks Bam, thanks fellow awreeoh!

2018-03-17 01:05 UTC, merged